name: Node.js CI/CD to Linux Server
on:
  push:
    branches: ["master"]
  # pull_request:
  #   branches: ["master", "dev"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    #==========build trên server của github===========
    - name: Checkout mã nguồn
      uses: actions/checkout@v4
      #môi trường ảo của git action
    - name: Cài đặt Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Cài đặt dependencies
      run: npm ci
      #clean + install
    - name: Build ứng dụng React
      run: npm run build
    #==========Đẩy thư mục dist lên Server Linux bằng giao thức SFTP/SSH===========
    - name: upload dist folder to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        password: ${{ secrets.SERVER_SSH_KEY }}
        source: "dist/*"                                 # Đẩy toàn bộ file trong dist
        target: "/var/www/SelfLearnChineseFE"            # Thư mục đích trên server Linux
        strip_components: 1                              # Bỏ qua việc tạo thêm thư mục 'dist/' trên server
